FROM docker.io/library/ubuntu@sha256:a08e551cb33850e4740772b38217fc1796a66da2506d312abe51acda354ff061

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        ca-certificates=20260601~24.04.1 \
        fpga-icestorm=0~20230218gitd20a5e9-1 \
        iverilog=12.0-2build2 \
        nextpnr-ice40=0.6-3build5 \
        ngspice=42+ds-3build1 \
        python3=3.12.3-0ubuntu2.1 \
        verilator=5.020-1 \
        yosys=0.33-5build2 \
    && install -d -m 0755 /usr/share/edagym \
    && dpkg-query --show --showformat='${binary:Package}\t${Version}\t${Architecture}\n' \
        | LC_ALL=C sort > /usr/share/edagym/dpkg-manifest.tsv \
    && sha256sum /usr/share/edagym/dpkg-manifest.tsv \
        | cut -d ' ' -f 1 > /usr/share/edagym/dpkg-manifest.sha256 \
    && rm -rf /var/lib/apt/lists/*
