"""Immutable workload descriptions and semantic result parsers."""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Iterable
from dataclasses import dataclass
from enum import StrEnum
from typing import Annotated, Literal, Protocol, Self

from pydantic import Field, field_validator, model_validator

from edagym.canonical import canonical_digest
from edagym.drivers.model import qualification_fixture_id
from edagym.drivers.semantic_claims import (
    SemanticJoint,
    claim_id_for_joints,
    normalize_semantic_joints,
)
from edagym.specs.common import (
    Capability,
    Digest,
    Identifier,
    SchemaVersion,
    StrictModel,
    validate_relative_path,
)

_IDENTIFIER = re.compile(r"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")


def _validate_identifier(value: str) -> None:
    if len(value) > 96 or _IDENTIFIER.fullmatch(value) is None:
        raise ValueError(f"invalid fixture identifier: {value!r}")


def qualification_artifact_id(fixture_id: str, local_id: str) -> str:
    """Derive a globally unique evidence identity from fixture-local names."""

    value = f"{fixture_id}.{local_id}"
    _validate_identifier(value)
    return value


class FixtureRole(StrEnum):
    """The two independent roles required to qualify one semantic joint."""

    ACCEPTANCE = "acceptance"
    REJECTION = "rejection"


class SemanticRejectionReason(StrEnum):
    """Semantic failures that a canonical parser may positively identify."""

    FUNCTIONAL_MISMATCH = "functional_mismatch"
    PROPERTY_COUNTEREXAMPLE = "property_counterexample"
    EQUIVALENCE_MISMATCH = "equivalence_mismatch"
    RULE_VIOLATION = "rule_violation"
    CLOCK_DOMAIN_CROSSING_VIOLATION = "clock_domain_crossing_violation"
    RESET_DOMAIN_CROSSING_VIOLATION = "reset_domain_crossing_violation"
    DEGENERATE_IMPLEMENTATION = "degenerate_implementation"
    MISSING_REQUIRED_STRUCTURE = "missing_required_structure"
    TIMING_PATH_MISSING = "timing_path_missing"
    TIMING_CONSTRAINT_VIOLATION = "timing_constraint_violation"
    ACTIVITY_COVERAGE_INCOMPLETE = "activity_coverage_incomplete"
    POWER_GRID_VIOLATION = "power_grid_violation"
    ANALOG_VALUE_OUT_OF_RANGE = "analog_value_out_of_range"
    IMPLEMENTATION_CONSTRAINT_VIOLATION = "implementation_constraint_violation"
    INCOMPLETE_SCAN_CHAIN = "incomplete_scan_chain"
    DFT_INVALID_SETUP = "dft_invalid_setup"
    RESOURCE_CAPACITY_EXCEEDED = "resource_capacity_exceeded"
    CIRCUIT_CONVERGENCE_FAILURE = "circuit_convergence_failure"
    LAYOUT_SCHEMATIC_MISMATCH = "layout_schematic_mismatch"
    CHARACTERIZATION_ARC_FAILURE = "characterization_arc_failure"


def qualification_case_id(
    tool_id: str,
    capability: Capability,
    role: FixtureRole,
) -> str:
    """Derive the immutable identity of one role in a qualification pair."""

    return f"{qualification_fixture_id(tool_id, capability)}_{role.value}"


@dataclass(frozen=True, slots=True)
class FixtureInput:
    """One trusted, built-in input materialized in a fresh workspace."""

    logical_id: str
    path: str
    content: bytes
    media_type: str = "text/plain"

    def __post_init__(self) -> None:
        _validate_identifier(self.logical_id)
        validate_relative_path(self.path)
        _validate_media_type(self.media_type)


@dataclass(frozen=True, slots=True)
class FixtureAssetInput:
    """One deployment-bound restricted asset copied into the private workspace."""

    logical_id: str
    path: str
    asset_id: str
    media_type: str = "application/octet-stream"

    def __post_init__(self) -> None:
        _validate_identifier(self.logical_id)
        validate_relative_path(self.path)
        _validate_identifier(self.asset_id)
        _validate_media_type(self.media_type)


@dataclass(frozen=True, slots=True)
class FixtureOutput:
    """A file whose bytes are evidence produced by the workload."""

    logical_id: str
    path: str
    required: bool = True
    media_type: str = "application/octet-stream"

    def __post_init__(self) -> None:
        _validate_identifier(self.logical_id)
        validate_relative_path(self.path)
        _validate_media_type(self.media_type)


@dataclass(frozen=True, slots=True)
class ToolInvocation:
    """Invoke the exact executable resolved by the backend probe."""

    arguments: tuple[str, ...]

    def __post_init__(self) -> None:
        _validate_arguments(self.arguments)


@dataclass(frozen=True, slots=True)
class WorkspaceInvocation:
    """Invoke a program generated by an earlier tool invocation."""

    executable: str
    arguments: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        validate_relative_path(self.executable)
        _validate_arguments(self.arguments)


FixtureInvocation = ToolInvocation | WorkspaceInvocation


@dataclass(frozen=True, slots=True)
class MarkerLogProjection:
    """Retain exact public markers while discarding all surrounding diagnostics."""

    markers: tuple[bytes, ...]

    def __post_init__(self) -> None:
        if (
            not self.markers
            or len(self.markers) != len(set(self.markers))
            or any(not marker or len(marker) > 256 or b"\n" in marker for marker in self.markers)
        ):
            raise ValueError("retained log markers must be unique bounded single-line values")

    def project(self, chunks: Iterable[bytes]) -> bytes:
        found = [False] * len(self.markers)
        overlap = max(len(marker) for marker in self.markers) - 1
        tail = b""
        for chunk in chunks:
            window = tail + chunk
            for index, marker in enumerate(self.markers):
                found[index] |= marker in window
            tail = window[-overlap:] if overlap else b""
        return b"".join(
            marker + b"\n" for marker, present in zip(self.markers, found, strict=True) if present
        )


class FixtureInputSnapshot(StrictModel):
    logical_id: Identifier
    path: str
    digest: Digest
    size_bytes: Annotated[int, Field(ge=0)]
    media_type: str

    @field_validator("path")
    @classmethod
    def normalize_path(cls, value: str) -> str:
        return validate_relative_path(value)

    @field_validator("media_type")
    @classmethod
    def normalize_media_type(cls, value: str) -> str:
        _validate_media_type(value)
        return value


class FixtureAssetInputSnapshot(StrictModel):
    logical_id: Identifier
    path: str
    asset_id: Identifier
    media_type: str

    @field_validator("path")
    @classmethod
    def normalize_path(cls, value: str) -> str:
        return validate_relative_path(value)

    @field_validator("media_type")
    @classmethod
    def normalize_media_type(cls, value: str) -> str:
        _validate_media_type(value)
        return value


class ToolInvocationSnapshot(StrictModel):
    kind: Literal["tool"] = "tool"
    arguments: tuple[str, ...]

    @field_validator("arguments")
    @classmethod
    def normalize_arguments(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        _validate_arguments(value)
        return value


class WorkspaceInvocationSnapshot(StrictModel):
    kind: Literal["workspace"] = "workspace"
    executable: str
    arguments: tuple[str, ...]

    @field_validator("executable")
    @classmethod
    def normalize_executable(cls, value: str) -> str:
        return validate_relative_path(value)

    @field_validator("arguments")
    @classmethod
    def normalize_arguments(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        _validate_arguments(value)
        return value


FixtureInvocationSnapshot = Annotated[
    ToolInvocationSnapshot | WorkspaceInvocationSnapshot,
    Field(discriminator="kind"),
]


class FixtureOutputSnapshot(StrictModel):
    logical_id: Identifier
    path: str
    required: bool
    media_type: str

    @field_validator("path")
    @classmethod
    def normalize_path(cls, value: str) -> str:
        return validate_relative_path(value)

    @field_validator("media_type")
    @classmethod
    def normalize_media_type(cls, value: str) -> str:
        _validate_media_type(value)
        return value


class QualificationFixtureSnapshot(StrictModel):
    schema_version: SchemaVersion = 1
    fixture_id: Identifier
    pair_id: Identifier
    tool_id: Identifier
    capability: Capability
    semantic_claim_id: Identifier
    semantic_joints: tuple[SemanticJoint, ...]
    role: FixtureRole
    rejection_reason: SemanticRejectionReason | None = None
    inputs: tuple[FixtureInputSnapshot, ...]
    restricted_assets: tuple[FixtureAssetInputSnapshot, ...] = Field(
        default=(),
        exclude_if=lambda value: not value,
    )
    invocations: tuple[FixtureInvocationSnapshot, ...]
    expected_exit_codes: tuple[int, ...]
    outputs: tuple[FixtureOutputSnapshot, ...]
    log_retention: Literal["full", "marker_projection"]
    retained_log_marker_digests: tuple[Digest, ...]
    parser_digest: Digest

    @field_validator("semantic_joints")
    @classmethod
    def normalize_claim_joints(
        cls,
        value: tuple[SemanticJoint, ...],
    ) -> tuple[SemanticJoint, ...]:
        if len(value) != len(set(value)):
            raise ValueError("qualification semantic joints must be unique")
        return tuple(sorted(value, key=lambda item: item.value))

    @model_validator(mode="after")
    def validate_contract(self) -> Self:
        if self.semantic_claim_id != claim_id_for_joints(
            self.capability,
            self.semantic_joints,
        ):
            raise ValueError("qualification semantic claim is not canonical")
        if self.pair_id != qualification_fixture_id(self.tool_id, self.capability):
            raise ValueError("qualification pair identity must be derived from tool capability")
        if self.fixture_id != qualification_case_id(
            self.tool_id,
            self.capability,
            self.role,
        ):
            raise ValueError("qualification case identity must include its evidence role")
        if (self.role is FixtureRole.REJECTION) != (self.rejection_reason is not None):
            raise ValueError("only rejection cases carry an expected semantic reason")
        if not self.inputs or not self.invocations:
            raise ValueError("qualification fixture snapshots require inputs and invocations")
        if (
            len(self.expected_exit_codes) != len(self.invocations)
            or any(
                isinstance(code, bool) or not isinstance(code, int) or code < 0 or code > 255
                for code in self.expected_exit_codes
            )
            or any(self.expected_exit_codes[:-1])
            or (self.role is FixtureRole.ACCEPTANCE and any(self.expected_exit_codes))
        ):
            raise ValueError("qualification exit codes must be role-bound completion statuses")
        input_ids = [item.logical_id for item in self.inputs]
        input_paths = [item.path for item in self.inputs]
        asset_ids = [item.logical_id for item in self.restricted_assets]
        asset_paths = [item.path for item in self.restricted_assets]
        output_ids = [item.logical_id for item in self.outputs]
        output_paths = [item.path for item in self.outputs]
        if len(input_ids) != len(set(input_ids)) or len(input_paths) != len(set(input_paths)):
            raise ValueError("qualification snapshot inputs must be unique")
        if len(asset_ids) != len(set(asset_ids)) or len(asset_paths) != len(set(asset_paths)):
            raise ValueError("qualification snapshot restricted assets must be unique")
        if len(output_ids) != len(set(output_ids)) or len(output_paths) != len(set(output_paths)):
            raise ValueError("qualification snapshot outputs must be unique")
        if (
            set(input_ids) & (set(asset_ids) | set(output_ids))
            or set(asset_ids) & set(output_ids)
            or set(input_paths) & (set(asset_paths) | set(output_paths))
            or set(asset_paths) & set(output_paths)
        ):
            raise ValueError("qualification snapshot input and output identities cannot overlap")
        generated = {
            item.executable
            for item in self.invocations
            if isinstance(item, WorkspaceInvocationSnapshot)
        }
        if not generated.issubset(set(output_paths)):
            raise ValueError("generated fixture programs must be declared as snapshot outputs")
        if (self.log_retention == "marker_projection") != bool(self.retained_log_marker_digests):
            raise ValueError("marker-projected logs require exact retained marker identities")
        return self

    @property
    def digest(self) -> str:
        return canonical_digest(self, domain="backend-qualification-fixture-v1")


@dataclass(frozen=True, slots=True)
class ObservedFile:
    path: str
    content: bytes
    size_bytes: int
    truncated: bool


@dataclass(frozen=True, slots=True)
class FixtureObservation:
    exit_codes: tuple[int, ...]
    stdout: tuple[bytes, ...]
    stderr: tuple[bytes, ...]
    files: tuple[ObservedFile, ...]

    def file(self, path: str) -> ObservedFile | None:
        return next((item for item in self.files if item.path == path), None)


class FixtureParser(Protocol):
    """Judge tool semantics without relying on diagnostic wording alone."""

    def accepts(self, observation: FixtureObservation) -> bool: ...

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None: ...


@dataclass(frozen=True, slots=True)
class MarkerParser:
    marker: bytes
    output_path: str | None = None
    output_token: bytes | None = None
    rejection_marker: bytes | None = None
    rejection_reason: SemanticRejectionReason | None = None
    rejection_exit_code: int = 0
    missing_output_token_rejection_reason: SemanticRejectionReason | None = None

    def __post_init__(self) -> None:
        if (self.rejection_marker is None) != (self.rejection_reason is None):
            raise ValueError("marker rejection requires both a marker and typed reason")
        if self.rejection_marker == self.marker:
            raise ValueError("acceptance and rejection markers must differ")
        if (
            isinstance(self.rejection_exit_code, bool)
            or not isinstance(self.rejection_exit_code, int)
            or self.rejection_exit_code < 0
            or self.rejection_exit_code > 255
        ):
            raise ValueError("semantic rejection exit code must be an unsigned process status")
        if self.missing_output_token_rejection_reason is not None and (
            self.output_path is None or self.output_token is None
        ):
            raise ValueError("missing-token rejection requires a declared output token")

    def accepts(self, observation: FixtureObservation) -> bool:
        if not observation.exit_codes or any(code != 0 for code in observation.exit_codes):
            return False
        if self.marker not in b"\n".join(observation.stdout):
            return False
        if self.rejection_marker is not None and self.rejection_marker in b"\n".join(
            (*observation.stdout, *observation.stderr)
        ):
            return False
        if self.output_path is None:
            return True
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return False
        return self.output_token is None or self.output_token in output.content

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if (
            not observation.exit_codes
            or any(code != 0 for code in observation.exit_codes[:-1])
            or observation.exit_codes[-1] != self.rejection_exit_code
        ):
            return None
        streams = b"\n".join((*observation.stdout, *observation.stderr))
        if (
            self.rejection_marker is not None
            and self.rejection_reason is not None
            and self.rejection_marker in streams
            and self.marker not in streams
        ):
            return self.rejection_reason
        if (
            self.missing_output_token_rejection_reason is not None
            and self.marker in streams
            and self.output_path is not None
            and self.output_token is not None
        ):
            output = observation.file(self.output_path)
            if (
                output is not None
                and not output.truncated
                and self.output_token not in output.content
            ):
                return self.missing_output_token_rejection_reason
        return None


@dataclass(frozen=True, slots=True)
class MarkerSetParser:
    """Require independent semantic markers from one successful invocation."""

    markers: tuple[bytes, ...]
    rejection_markers: tuple[bytes, ...] = ()
    rejection_reason: SemanticRejectionReason | None = None

    def __post_init__(self) -> None:
        if len(self.markers) < 2 or len(self.markers) != len(set(self.markers)):
            raise ValueError("marker-set parsers require unique independent markers")
        if (not self.rejection_markers) != (self.rejection_reason is None):
            raise ValueError("marker-set rejection requires markers and a typed reason")
        if len(self.rejection_markers) != len(set(self.rejection_markers)):
            raise ValueError("marker-set rejection markers must be unique")
        if set(self.markers) & set(self.rejection_markers):
            raise ValueError("acceptance and rejection marker sets cannot overlap")

    def accepts(self, observation: FixtureObservation) -> bool:
        stdout = b"\n".join((*observation.stdout, *observation.stderr))
        return (
            observation.exit_codes == (0,)
            and all(marker in stdout for marker in self.markers)
            and not any(marker in stdout for marker in self.rejection_markers)
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        streams = b"\n".join((*observation.stdout, *observation.stderr))
        if (
            observation.exit_codes == (0,)
            and self.rejection_reason is not None
            and all(marker in streams for marker in self.rejection_markers)
            and not any(marker in streams for marker in self.markers)
        ):
            return self.rejection_reason
        return None


@dataclass(frozen=True, slots=True)
class SemanticTokenParser:
    """Classify a completed workload from mutually exclusive semantic tokens."""

    completion_marker: bytes
    acceptance_token: bytes
    rejection_token: bytes
    rejection_reason: SemanticRejectionReason

    def __post_init__(self) -> None:
        values = (self.completion_marker, self.acceptance_token, self.rejection_token)
        if any(not value for value in values) or len(values) != len(set(values)):
            raise ValueError("semantic outcome tokens must be distinct and non-empty")

    def accepts(self, observation: FixtureObservation) -> bool:
        streams = b"\n".join((*observation.stdout, *observation.stderr))
        return (
            observation.exit_codes == (0,)
            and self.completion_marker in streams
            and self.acceptance_token in streams
            and self.rejection_token not in streams
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        streams = b"\n".join((*observation.stdout, *observation.stderr))
        if (
            observation.exit_codes == (0,)
            and self.completion_marker in streams
            and self.rejection_token in streams
            and self.acceptance_token not in streams
        ):
            return self.rejection_reason
        return None


@dataclass(frozen=True, slots=True)
class YosysNetlistParser:
    marker: bytes
    output_path: str
    module_name: str

    def accepts(self, observation: FixtureObservation) -> bool:
        if observation.exit_codes != (0,) or self.marker not in b"\n".join(observation.stdout):
            return False
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return False
        try:
            document = json.loads(output.content)
            module = document["modules"][self.module_name]
            cells = module["cells"]
        except (KeyError, TypeError, json.JSONDecodeError, UnicodeDecodeError):
            return False
        return isinstance(cells, dict) and bool(cells)

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if observation.exit_codes != (0,) or self.marker not in b"\n".join(observation.stdout):
            return None
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return None
        try:
            cells = json.loads(output.content)["modules"][self.module_name]["cells"]
        except (KeyError, TypeError, json.JSONDecodeError, UnicodeDecodeError):
            return None
        return (
            SemanticRejectionReason.DEGENERATE_IMPLEMENTATION
            if isinstance(cells, dict) and not cells
            else None
        )


@dataclass(frozen=True, slots=True)
class AbcSynthesisParser:
    marker: bytes
    output_path: str
    model_name: str

    def accepts(self, observation: FixtureObservation) -> bool:
        if observation.exit_codes != (0,) or self.marker not in b"\n".join(observation.stdout):
            return False
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return False
        lines = tuple(line.strip() for line in output.content.splitlines())
        logic_covers = [
            line for line in lines if line.startswith(b".names ") and len(line.split()) >= 3
        ]
        return (
            f".model {self.model_name}".encode() in lines
            and any(line.startswith(b".inputs ") for line in lines)
            and any(line.startswith(b".outputs ") for line in lines)
            and bool(logic_covers)
            and b".end" in lines
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if observation.exit_codes != (0,) or self.marker not in b"\n".join(observation.stdout):
            return None
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return None
        lines = tuple(line.strip() for line in output.content.splitlines())
        valid_shell = (
            f".model {self.model_name}".encode() in lines
            and any(line.startswith(b".inputs ") for line in lines)
            and any(line.startswith(b".outputs ") for line in lines)
            and b".end" in lines
        )
        has_logic_cover = any(
            line.startswith(b".names ") and len(line.split()) >= 3 for line in lines
        )
        if valid_shell and not has_logic_cover:
            return SemanticRejectionReason.DEGENERATE_IMPLEMENTATION
        return None


@dataclass(frozen=True, slots=True)
class AbcEquivalenceParser:
    marker: bytes
    equivalence_token: bytes
    mismatch_token: bytes = b"Networks are NOT EQUIVALENT"

    def accepts(self, observation: FixtureObservation) -> bool:
        stdout = b"\n".join(observation.stdout)
        return (
            observation.exit_codes == (0,)
            and self.marker in stdout
            and self.equivalence_token in stdout
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        stdout = b"\n".join(observation.stdout)
        if (
            observation.exit_codes == (0,)
            and self.marker in stdout
            and self.mismatch_token in stdout
            and self.equivalence_token not in stdout
        ):
            return SemanticRejectionReason.EQUIVALENCE_MISMATCH
        return None


@dataclass(frozen=True, slots=True)
class YosysEquivalenceParser:
    marker: bytes
    proven_token: bytes = b"Equivalence successfully proven!"
    mismatch_token: bytes = b"Found a total of"

    def accepts(self, observation: FixtureObservation) -> bool:
        stdout = b"\n".join(observation.stdout)
        return (
            observation.exit_codes == (0,)
            and self.marker in stdout
            and self.proven_token in stdout
            and self.mismatch_token not in stdout
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        stdout = b"\n".join(observation.stdout)
        if (
            observation.exit_codes == (0,)
            and self.marker in stdout
            and self.mismatch_token in stdout
            and self.proven_token not in stdout
        ):
            return SemanticRejectionReason.EQUIVALENCE_MISMATCH
        return None


@dataclass(frozen=True, slots=True)
class FirtoolLoweringParser:
    output_path: str
    module_declaration: bytes
    sequential_token: bytes

    def accepts(self, observation: FixtureObservation) -> bool:
        if observation.exit_codes != (0,):
            return False
        output = observation.file(self.output_path)
        return (
            output is not None
            and not output.truncated
            and self.module_declaration in output.content
            and self.sequential_token in output.content
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if observation.exit_codes != (0,):
            return None
        output = observation.file(self.output_path)
        if (
            output is not None
            and not output.truncated
            and self.module_declaration in output.content
            and self.sequential_token not in output.content
        ):
            return SemanticRejectionReason.MISSING_REQUIRED_STRUCTURE
        return None


@dataclass(frozen=True, slots=True)
class VerilatorLintParser:
    output_path: str
    module_name: str
    rejection_marker: bytes = b"%Warning-LATCH:"

    def accepts(self, observation: FixtureObservation) -> bool:
        if not observation.exit_codes or any(observation.exit_codes):
            return False
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return False
        try:
            root = json.loads(output.content)
            modules = root["modulesp"]
        except (json.JSONDecodeError, KeyError, TypeError, UnicodeDecodeError):
            return False
        warnings = b"\n".join((*observation.stdout, *observation.stderr))
        return (
            self.rejection_marker not in warnings
            and isinstance(modules, list)
            and any(
                isinstance(module, dict) and module.get("origName") == self.module_name
                for module in modules
            )
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if not observation.exit_codes or any(observation.exit_codes):
            return None
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return None
        try:
            modules = json.loads(output.content)["modulesp"]
        except (json.JSONDecodeError, KeyError, TypeError, UnicodeDecodeError):
            return None
        streams = b"\n".join((*observation.stdout, *observation.stderr))
        if (
            self.rejection_marker in streams
            and isinstance(modules, list)
            and any(
                isinstance(module, dict) and module.get("origName") == self.module_name
                for module in modules
            )
        ):
            return SemanticRejectionReason.RULE_VIOLATION
        return None


@dataclass(frozen=True, slots=True)
class KlayoutDrcParser:
    output_path: str
    rule_id: str

    def _violation_count(self, observation: FixtureObservation) -> int | None:
        if observation.exit_codes != (0,):
            return None
        output = observation.file(self.output_path)
        if output is None or output.truncated:
            return None
        try:
            report = json.loads(output.content)
        except (json.JSONDecodeError, UnicodeDecodeError):
            return None
        if not isinstance(report, dict) or set(report) != {
            "engine",
            "engine_version",
            "minimum_spacing_nm",
            "rule_id",
            "violation_count",
        }:
            return None
        count = report["violation_count"]
        minimum = report["minimum_spacing_nm"]
        if (
            report["engine"] != "klayout.db"
            or report["rule_id"] != self.rule_id
            or not isinstance(report["engine_version"], str)
            or not report["engine_version"]
            or isinstance(minimum, bool)
            or not isinstance(minimum, int)
            or minimum <= 0
            or isinstance(count, bool)
            or not isinstance(count, int)
            or count < 0
        ):
            return None
        return int(count)

    def accepts(self, observation: FixtureObservation) -> bool:
        return self._violation_count(observation) == 0

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        count = self._violation_count(observation)
        if count is not None and count > 0:
            return SemanticRejectionReason.RULE_VIOLATION
        return None


@dataclass(frozen=True, slots=True)
class JasperPropertyStatusParser:
    property_name: str
    expected_status: bytes
    rejection_status: bytes = b"cex"

    def accepts(self, observation: FixtureObservation) -> bool:
        if observation.exit_codes != (0,):
            return False
        expected = (
            b"EDAGYM_JASPER_PROPERTY_STATUS "
            + self.property_name.encode()
            + b" "
            + self.expected_status
        )
        return expected in b"\n".join(observation.stdout)

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if observation.exit_codes != (0,):
            return None
        expected = (
            b"EDAGYM_JASPER_PROPERTY_STATUS "
            + self.property_name.encode()
            + b" "
            + self.rejection_status
        )
        if expected in b"\n".join(observation.stdout):
            return SemanticRejectionReason.PROPERTY_COUNTEREXAMPLE
        return None


@dataclass(frozen=True, slots=True)
class JasperCdcStatusParser:
    expected_violation_count: int
    pass_marker: bytes

    def accepts(self, observation: FixtureObservation) -> bool:
        if observation.exit_codes != (0,):
            return False
        count_marker = b"EDAGYM_CDC_VIOLATION_COUNT "
        count = None
        for line in b"\n".join(observation.stdout).splitlines():
            if line.startswith(count_marker):
                try:
                    count = int(line[len(count_marker) :])
                except ValueError:
                    return False
        return count == self.expected_violation_count and self.pass_marker in b"\n".join(
            observation.stdout
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if observation.exit_codes != (0,) or self.pass_marker not in b"\n".join(observation.stdout):
            return None
        count_marker = b"EDAGYM_CDC_VIOLATION_COUNT "
        counts: list[int] = []
        for line in b"\n".join(observation.stdout).splitlines():
            if line.startswith(count_marker):
                try:
                    counts.append(int(line[len(count_marker) :]))
                except ValueError:
                    return None
        if len(counts) == 1 and counts[0] > self.expected_violation_count:
            return SemanticRejectionReason.RULE_VIOLATION
        return None


@dataclass(frozen=True, slots=True)
class SpyglassStatusParser:
    status_marker: bytes
    rejection_marker: bytes = b"SpyGlass Exit Code 0 (Rule-checking completed with errors)"

    def accepts(self, observation: FixtureObservation) -> bool:
        return observation.exit_codes == (0,) and self.status_marker in b"\n".join(
            observation.stdout
        )

    def rejection(
        self,
        observation: FixtureObservation,
    ) -> SemanticRejectionReason | None:
        if observation.exit_codes == (0,) and self.rejection_marker in b"\n".join(
            observation.stdout
        ):
            return SemanticRejectionReason.RULE_VIOLATION
        return None


@dataclass(frozen=True, slots=True)
class QualificationFixture:
    tool_id: str
    capability: Capability
    inputs: tuple[FixtureInput, ...]
    invocations: tuple[FixtureInvocation, ...]
    outputs: tuple[FixtureOutput, ...]
    parser: FixtureParser
    semantic_joints: tuple[SemanticJoint, ...] = ()
    restricted_assets: tuple[FixtureAssetInput, ...] = ()
    rejection_inputs: tuple[FixtureInput, ...] = ()
    rejection_reason: SemanticRejectionReason | None = None
    rejection_exit_code: int = 0
    log_projection: MarkerLogProjection | None = None

    def __post_init__(self) -> None:
        _validate_identifier(self.tool_id)
        if normalize_semantic_joints(self.capability, self.semantic_joints) != (
            self.semantic_joints
        ):
            raise ValueError("qualification semantic joints must use canonical order")
        if not self.inputs or not self.invocations:
            raise ValueError("qualification fixtures require inputs and invocations")
        input_ids = [item.logical_id for item in self.inputs]
        input_paths = [item.path for item in self.inputs]
        output_ids = [item.logical_id for item in self.outputs]
        output_paths = [item.path for item in self.outputs]
        asset_ids = [item.logical_id for item in self.restricted_assets]
        asset_paths = [item.path for item in self.restricted_assets]
        bound_asset_ids = [item.asset_id for item in self.restricted_assets]
        if len(input_ids) != len(set(input_ids)) or len(input_paths) != len(set(input_paths)):
            raise ValueError("qualification fixture inputs must be unique")
        if len(output_ids) != len(set(output_ids)) or len(output_paths) != len(set(output_paths)):
            raise ValueError("qualification fixture outputs must be unique")
        if (
            len(asset_ids) != len(set(asset_ids))
            or len(asset_paths) != len(set(asset_paths))
            or len(bound_asset_ids) != len(set(bound_asset_ids))
        ):
            raise ValueError("qualification fixture restricted assets must be unique")
        if (
            set(input_ids) & (set(asset_ids) | set(output_ids))
            or set(asset_ids) & set(output_ids)
            or set(input_paths) & (set(asset_paths) | set(output_paths))
            or set(asset_paths) & set(output_paths)
        ):
            raise ValueError("qualification inputs and outputs must be disjoint")
        if bool(self.rejection_inputs) != (self.rejection_reason is not None):
            raise ValueError("qualification rejection requires inputs and a typed reason")
        if (
            isinstance(self.rejection_exit_code, bool)
            or not isinstance(self.rejection_exit_code, int)
            or self.rejection_exit_code < 0
            or self.rejection_exit_code > 255
            or (not self.rejection_inputs and self.rejection_exit_code != 0)
        ):
            raise ValueError("semantic rejection exit code requires a paired fixture")
        if self.rejection_inputs:
            rejection_shape = tuple(
                (item.logical_id, item.path, item.media_type) for item in self.rejection_inputs
            )
            acceptance_shape = tuple(
                (item.logical_id, item.path, item.media_type) for item in self.inputs
            )
            if rejection_shape != acceptance_shape:
                raise ValueError("qualification pair must use one input topology")
            if all(
                rejected.content == accepted.content
                for accepted, rejected in zip(
                    self.inputs,
                    self.rejection_inputs,
                    strict=True,
                )
            ):
                raise ValueError("qualification rejection must change trusted input content")
        generated_programs = {
            item.executable for item in self.invocations if isinstance(item, WorkspaceInvocation)
        }
        if not generated_programs.issubset(set(output_paths)):
            raise ValueError("generated fixture programs must be declared as evidence outputs")

    @property
    def fixture_id(self) -> str:
        return qualification_fixture_id(self.tool_id, self.capability)

    @property
    def snapshot(self) -> QualificationFixtureSnapshot:
        return self.snapshot_for(FixtureRole.ACCEPTANCE)

    def snapshot_for(self, role: FixtureRole) -> QualificationFixtureSnapshot:
        inputs = self.inputs_for(role)
        case_id = qualification_case_id(self.tool_id, self.capability, role)
        return QualificationFixtureSnapshot(
            fixture_id=case_id,
            pair_id=self.fixture_id,
            tool_id=self.tool_id,
            capability=self.capability,
            semantic_claim_id=self.resolved_semantic_claim_id,
            semantic_joints=self.semantic_joints,
            role=role,
            rejection_reason=(self.rejection_reason if role is FixtureRole.REJECTION else None),
            inputs=tuple(
                FixtureInputSnapshot(
                    logical_id=qualification_artifact_id(case_id, item.logical_id),
                    path=item.path,
                    digest=_digest_bytes(item.content),
                    size_bytes=len(item.content),
                    media_type=item.media_type,
                )
                for item in inputs
            ),
            restricted_assets=tuple(
                FixtureAssetInputSnapshot(
                    logical_id=qualification_artifact_id(case_id, item.logical_id),
                    path=item.path,
                    asset_id=item.asset_id,
                    media_type=item.media_type,
                )
                for item in self.restricted_assets
            ),
            invocations=tuple(_invocation_snapshot(item) for item in self.invocations),
            expected_exit_codes=self.exit_codes_for(role),
            outputs=tuple(
                FixtureOutputSnapshot(
                    logical_id=qualification_artifact_id(case_id, item.logical_id),
                    path=item.path,
                    required=item.required,
                    media_type=item.media_type,
                )
                for item in self.outputs
            ),
            log_retention=("marker_projection" if self.log_projection is not None else "full"),
            retained_log_marker_digests=(
                tuple(_digest_bytes(marker) for marker in self.log_projection.markers)
                if self.log_projection is not None
                else ()
            ),
            parser_digest=canonical_digest(
                _parser_identity(self.parser),
                domain="backend-qualification-parser-v1",
            ),
        )

    @property
    def digest(self) -> str:
        if not self.rejection_inputs:
            return canonical_digest(
                {"acceptance": self.snapshot},
                domain="backend-qualification-pair-v1",
            )
        return canonical_digest(
            {
                "acceptance": self.snapshot_for(FixtureRole.ACCEPTANCE),
                "rejection": self.snapshot_for(FixtureRole.REJECTION),
            },
            domain="backend-qualification-pair-v1",
        )

    @property
    def resolved_semantic_claim_id(self) -> str:
        return claim_id_for_joints(self.capability, self.semantic_joints)

    def inputs_for(self, role: FixtureRole) -> tuple[FixtureInput, ...]:
        if role is FixtureRole.ACCEPTANCE:
            return self.inputs
        if not self.rejection_inputs:
            raise ValueError("qualification fixture has no rejection workload")
        return self.rejection_inputs

    def exit_codes_for(self, role: FixtureRole) -> tuple[int, ...]:
        final_code = self.rejection_exit_code if role is FixtureRole.REJECTION else 0
        return (0,) * (len(self.invocations) - 1) + (final_code,)


def _invocation_snapshot(invocation: FixtureInvocation) -> FixtureInvocationSnapshot:
    if isinstance(invocation, ToolInvocation):
        return ToolInvocationSnapshot(arguments=invocation.arguments)
    return WorkspaceInvocationSnapshot(
        executable=invocation.executable,
        arguments=invocation.arguments,
    )


def _parser_identity(parser: FixtureParser) -> dict[str, object]:
    identity_owner = getattr(parser, "qualification_identity", None)
    if identity_owner is not None:
        if not callable(identity_owner):
            raise TypeError("qualification parser identity owner must be callable")
        identity = identity_owner()
        if (
            not isinstance(identity, dict)
            or not identity
            or not isinstance(identity.get("kind"), str)
        ):
            raise TypeError("qualification parser identity must be a named mapping")
        _validate_identifier(identity["kind"])
        return identity
    if isinstance(parser, MarkerParser):
        return {
            "kind": "marker",
            "marker_digest": _digest_bytes(parser.marker),
            "output_path": parser.output_path,
            "output_token_digest": (
                _digest_bytes(parser.output_token) if parser.output_token is not None else None
            ),
            "rejection_marker_digest": (
                _digest_bytes(parser.rejection_marker)
                if parser.rejection_marker is not None
                else None
            ),
            "rejection_reason": parser.rejection_reason,
            "rejection_exit_code": parser.rejection_exit_code,
            "missing_output_token_rejection_reason": (parser.missing_output_token_rejection_reason),
        }
    if isinstance(parser, MarkerSetParser):
        return {
            "kind": "marker_set",
            "marker_digests": tuple(_digest_bytes(marker) for marker in parser.markers),
            "rejection_marker_digests": tuple(
                _digest_bytes(marker) for marker in parser.rejection_markers
            ),
            "rejection_reason": parser.rejection_reason,
        }
    if isinstance(parser, SemanticTokenParser):
        return {
            "kind": "semantic_token",
            "completion_marker_digest": _digest_bytes(parser.completion_marker),
            "acceptance_token_digest": _digest_bytes(parser.acceptance_token),
            "rejection_token_digest": _digest_bytes(parser.rejection_token),
            "rejection_reason": parser.rejection_reason,
        }
    if isinstance(parser, YosysNetlistParser):
        return {
            "kind": "yosys_netlist",
            "marker_digest": _digest_bytes(parser.marker),
            "output_path": parser.output_path,
            "module_name": parser.module_name,
            "rejection_reason": SemanticRejectionReason.DEGENERATE_IMPLEMENTATION,
        }
    if isinstance(parser, AbcSynthesisParser):
        return {
            "kind": "abc_synthesis",
            "marker_digest": _digest_bytes(parser.marker),
            "output_path": parser.output_path,
            "model_name": parser.model_name,
            "rejection_reason": SemanticRejectionReason.DEGENERATE_IMPLEMENTATION,
        }
    if isinstance(parser, AbcEquivalenceParser):
        return {
            "kind": "abc_equivalence",
            "marker_digest": _digest_bytes(parser.marker),
            "equivalence_token_digest": _digest_bytes(parser.equivalence_token),
            "mismatch_token_digest": _digest_bytes(parser.mismatch_token),
            "rejection_reason": SemanticRejectionReason.EQUIVALENCE_MISMATCH,
        }
    if isinstance(parser, YosysEquivalenceParser):
        return {
            "kind": "yosys_equivalence",
            "marker_digest": _digest_bytes(parser.marker),
            "proven_token_digest": _digest_bytes(parser.proven_token),
            "mismatch_token_digest": _digest_bytes(parser.mismatch_token),
            "rejection_reason": SemanticRejectionReason.EQUIVALENCE_MISMATCH,
        }
    if isinstance(parser, FirtoolLoweringParser):
        return {
            "kind": "firtool_lowering",
            "output_path": parser.output_path,
            "module_declaration_digest": _digest_bytes(parser.module_declaration),
            "sequential_token_digest": _digest_bytes(parser.sequential_token),
            "rejection_reason": SemanticRejectionReason.MISSING_REQUIRED_STRUCTURE,
        }
    if isinstance(parser, VerilatorLintParser):
        return {
            "kind": "verilator_lint",
            "output_path": parser.output_path,
            "module_name": parser.module_name,
            "rejection_marker_digest": _digest_bytes(parser.rejection_marker),
            "rejection_reason": SemanticRejectionReason.RULE_VIOLATION,
        }
    if isinstance(parser, KlayoutDrcParser):
        return {
            "kind": "klayout_drc",
            "output_path": parser.output_path,
            "rule_id": parser.rule_id,
            "rejection_reason": SemanticRejectionReason.RULE_VIOLATION,
        }
    if isinstance(parser, JasperPropertyStatusParser):
        return {
            "kind": "jasper_property_status",
            "property_name": parser.property_name,
            "expected_status_digest": _digest_bytes(parser.expected_status),
            "rejection_status_digest": _digest_bytes(parser.rejection_status),
            "rejection_reason": SemanticRejectionReason.PROPERTY_COUNTEREXAMPLE,
        }
    if isinstance(parser, JasperCdcStatusParser):
        return {
            "kind": "jasper_cdc_status",
            "expected_violation_count": parser.expected_violation_count,
            "pass_marker_digest": _digest_bytes(parser.pass_marker),
            "rejection_reason": SemanticRejectionReason.RULE_VIOLATION,
        }
    if isinstance(parser, SpyglassStatusParser):
        return {
            "kind": "spyglass_status",
            "status_marker_digest": _digest_bytes(parser.status_marker),
            "rejection_marker_digest": _digest_bytes(parser.rejection_marker),
            "rejection_reason": SemanticRejectionReason.RULE_VIOLATION,
        }
    raise TypeError("qualification parser has no canonical identity")


def _digest_bytes(value: bytes) -> str:
    return f"sha256:{hashlib.sha256(value).hexdigest()}"


def _validate_arguments(arguments: tuple[str, ...]) -> None:
    if any("\x00" in item or "\n" in item or "\r" in item for item in arguments):
        raise ValueError("qualification command arguments cannot contain control boundaries")


def _validate_media_type(value: str) -> None:
    if not value or len(value) > 127 or "\n" in value or "\r" in value:
        raise ValueError("qualification artifact media types must be normalized")
